version: 0.0
os: linux
files:
  - source: ./webapp/NoteApp_Production/aws
    destination: /home/centos/WebApp
  - source: cloudwatch-config.json
    destination: /home/centos/WebApp
hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: root
  ApplicationStop:
    - location: ./stop_service.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./start_service.sh
      timeout: 300
      runas: root
