version: 0.0
os: linux
files:
  - source: ./webapp/NoteApp_Production/aws
    destination: /home/centos/WebApp
  - source: cloudwatch-config.json
    destination: /home/centos/WebApp
hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
